#!/usr/bin/env python3

""" Command line tool to list all Weight Log user. """

# pylint: disable=invalid-name

# Standard library imports
import argparse
import sys

# 3rd party imports
from tabulate import tabulate

# Local imports
from service import Service
from service.error import WeightLogError

# pylint: disable=missing-function-docstring
def main() -> None:
    # Parse command line
    parser = argparse.ArgumentParser(prog='wl-list-users',
        description='List Weight Log users.')
    parser.parse_args()

    # Delete user.
    return_code: int = 0
    try:
        service = Service()
        users = [user.flatten() for user in service.user_manager.get_users()]
        print(
            tabulate(
                users,
                headers = [
                    'ID',
                    'Username',
                    'Units',
                    'Goal Weight',
                    'Password'
                ],
                tablefmt = "github",
                numalign = "right",
                stralign = "right",
                floatfmt= (",.1f"),
            )
        )

    except WeightLogError as ex:
        print(f'ERROR: {ex}', file=sys.stderr)
        return_code = ex.return_code
    except KeyboardInterrupt:
        print('')
        return_code = -1

    sys.exit(return_code)

if __name__ == '__main__':
    main()
